### ISSUE TITLE
Error when updating

### ISSUE THREAD

**Issue by sirinath** [mamba-org/mamba#1286]
I am getting the following error:

```
numpy-base               [>                   ] (05m:04s) Failure when receiving data from the peer
scipy                    [=>                  ] (04m:39s)    837 KB /     14 MB (  1.56 KB/s)
xarray                   [====>               ] (01m:56s)    125 KB /    557 KB (237.00  B/s)
dask-core                [======>             ] (01m:51s)    237 KB /    718 KB (447.00  B/s)

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "C:\ProgramData\Miniconda3\lib\site-packages\mamba\mamba.py", line 897, in exception_converter
        raise e
      File "C:\ProgramData\Miniconda3\lib\site-packages\mamba\mamba.py", line 891, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "C:\ProgramData\Miniconda3\lib\site-packages\mamba\mamba.py", line 850, in _wrapped_main
        result = do_call(args, p)
      File "C:\ProgramData\Miniconda3\lib\site-packages\mamba\mamba.py", line 737, in do_call
        exit_code = update(args, parser)
      File "C:\ProgramData\Miniconda3\lib\site-packages\mamba\mamba.py", line 655, in update
        return install(args, parser, "update")
      File "C:\ProgramData\Miniconda3\lib\site-packages\mamba\mamba.py", line 589, in install
        downloaded = transaction.prompt(repos)
    RuntimeError: The process cannot access the file because it is being used by another process.
    : 'C:\ProgramData\Miniconda3\pkgs\numpy-base-1.20.3-py39hc2deb75_0.conda'

`$ C:\ProgramData\Miniconda3\Scripts\mamba update --all`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_BAT=C:\ProgramData\Miniconda3\condabin\conda.bat
                CONDA_EXE=C:\ProgramData\Miniconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\ProgramData\Miniconda3\condabin\..\Scripts\conda.exe"
               CONDA_ROOT=C:\ProgramData\Miniconda3
              CONDA_SHLVL=0
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\...
          MOZ_PLUGIN_PATH=...
                     PATH=C:\ProgramData\Miniconda3;C:\ProgramData\Miniconda3\Library\mingw-w64\
                          bin;C:\ProgramData\Miniconda3\Library\usr\bin;C:\ProgramData\Miniconda
                          3\Library\bin;C:\ProgramData\Miniconda3\Scripts;C:\ProgramData\Minicon
                          da3\bin;C:\ProgramData\Miniconda3\condabin;...;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\Syst
                          em32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\WINDOWS\S
                          ystem32\Wbem;...
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
    VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\

     active environment : None
            shell level : 0
       user config file : C:\Users\...\.condarc
 populated config files :
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.4.final.0
       virtual packages : __cuda=11.4=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\ProgramData\Miniconda3  (writable)
      conda av data dir : C:\ProgramData\Miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Miniconda3\pkgs
                          C:\Users\...\.conda\pkgs
                          C:\Users\...\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Miniconda3\envs
                          C:\Users\...\.conda\envs
                          C:\Users\...\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.9.4 Windows/10 Windows/10.0.19041
          administrator : True
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

**Comment by wolfv** [comment]
Do you know if you are on mamba 0.18.1?

**Comment by sirinath** [comment]
I am on 0.11.3

**Comment by wolfv** [comment]
Hm, that's a pretty old version. 

Are you running multiple `mamba` or `conda` processes in parallel?

**Comment by sirinath** [comment]
> Are you running multiple mamba or conda processes in parallel?

No.

I ran `mamba update mamba` before running. This does not seam to have worked then. I now ran ``conda update mamba`.

**Comment by adriendelsalle** [comment]
> numpy-base               [>                   ] (05m:04s) Failure when receiving data from the peer
scipy                    [=>                  ] (04m:39s)    837 KB /     14 MB (  1.56 KB/s)
xarray                   [====>               ] (01m:56s)    125 KB /    557 KB (237.00  B/s)
dask-core                [======>             ] (01m:51s)    237 KB /    718 KB (447.00  B/s)

Looks like you have a pretty bad internet connection.
Could you please :
- give use a reproducible set of instructions
- add verbosity with `-vvv` to get trace logs and copy paste the output here

I can't reproduce it locally by running
```bash
adrien@tower:~$ micromamba create -n oldmamba mamba=0.11.3 -y
(...)
adrien@tower:~$ micromamba activate oldmamba
adrien@tower:~$ mamba update mamba -q -y

(oldmamba) adrien@tower:~$ mamba update mamba -q -y
  Package       Version  Build           Channel                    Size
──────────────────────────────────────────────────────────────────────────
  Install:
──────────────────────────────────────────────────────────────────────────

  libmamba       0.18.1  h3985d26_1      conda-forge/linux-64       1 MB
  libmambapy     0.18.1  py39h8bfa403_1  conda-forge/linux-64     313 KB
  pybind11-abi        4  hd8ed1ab_3      conda-forge/noarch        10 KB
  yaml-cpp        0.6.3  he1b5a44_4      conda-forge/linux-64     208 KB

  Upgrade:
──────────────────────────────────────────────────────────────────────────

  mamba          0.11.3  py39h951de11_0  installed                      
  mamba          0.18.1  py39hfa8f2c8_1  conda-forge/linux-64      41 KB

  Summary:

  Install: 4 packages
  Upgrade: 1 packages

  Total download: 2 MB

──────────────────────────────────────────────────────────────────────────

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

```

**Comment by wolfv** [comment]
@sirinath you can find why mamba is not updated to the latest version in your environment when forcing an upgrade to `mamba=0.18`. Could you also try that?

**Comment by sirinath** [comment]
`conda update --all` updated `mamba` also. I have a 100 Mbps connection. When updating with `conda` it was fast and did not encountered the above error.

**Comment by sirinath** [comment]
The packages installed are (unfortunately the versions are updated now):

```
# packages in environment at C:\ProgramData\Miniconda3:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
altair                    4.1.0                      py_1
anaconda-client           1.8.0              pyhd8ed1ab_0    conda-forge
anaconda-navigator        2.1.1                    py39_0
ansi2html                 1.6.0            py39hcbf5309_2    conda-forge
antlr-python-runtime      4.7.2           py39hcbf5309_1003    conda-forge
anyio                     3.3.4            py39hcbf5309_1    conda-forge
argh                      0.26.2          pyh9f0ad1d_1002    conda-forge
argon2-cffi               21.1.0           py39hb82d6ee_2    conda-forge
arrow                     1.2.1              pyhd8ed1ab_0    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
astroid                   2.5.8            py39hcbf5309_0    conda-forge
async_generator           1.10                       py_0    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
autopep8                  1.6.0              pyhd8ed1ab_0    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bcrypt                    3.2.0            py39hb82d6ee_2    conda-forge
binaryornot               0.4.4                      py_1    conda-forge
black                     21.11b0            pyhd8ed1ab_0    conda-forge
blas                      1.0                         mkl
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
bokeh                     2.4.1            py39hcbf5309_2    conda-forge
bottleneck                1.3.2            py39h7cc1a96_1
brotli-python             1.0.9            py39h415ef7b_6    conda-forge
brotlipy                  0.7.0           py39hb82d6ee_1003    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
cartopy                   0.18.0           py39h80a4efb_1
certifi                   2021.10.8        py39hcbf5309_1    conda-forge
cf-units                  3.0.1            py39h5d4886f_1    conda-forge
cffi                      1.15.0           py39h0878f49_0    conda-forge
cftime                    1.2.1            py39h8512cfa_1    conda-forge
chardet                   4.0.0            py39hcbf5309_2    conda-forge
charset-normalizer        2.0.0              pyhd8ed1ab_0    conda-forge
chart-studio              1.1.0                      py_0    plotly
click                     8.0.3            py39hcbf5309_1    conda-forge
cloudpickle               2.0.0              pyhd8ed1ab_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
colorlover                0.3.0                      py_0    conda-forge
conda                     4.10.3           py39hcbf5309_4    conda-forge
conda-content-trust       0.1.3              pyhd8ed1ab_0    conda-forge
conda-package-handling    1.7.3            py39hb3671d1_1    conda-forge
conda-repo-cli            1.0.4              pyhd3eb1b0_0
conda-token               0.3.0              pyhd3eb1b0_0
console_shortcut          0.1.1                         4
cookiecutter              1.7.3              pyh6c4a22f_0    conda-forge
cryptography              35.0.0           py39h7bc7c5c_2    conda-forge
cufflinks-py              0.17.3                     py_0    conda-forge
curl                      7.80.0               h789b8ee_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.11.2           py39hb82d6ee_1    conda-forge
dash                      2.0.0              pyhd8ed1ab_0    conda-forge
dask                      2021.10.0          pyhd3eb1b0_0
dask-core                 2021.10.0          pyhd8ed1ab_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
debugpy                   1.5.1            py39h415ef7b_0    conda-forge
decorator                 5.1.0              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
diff-match-patch          20200713           pyh9f0ad1d_0    conda-forge
distributed               2021.10.0        py39haa95532_0
docutils                  0.15.2           py39hcbf5309_2    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
expat                     2.4.1                h39d44d4_0    conda-forge
fasteners                 0.16               pyhd8ed1ab_0    conda-forge
flake8                    3.9.2              pyhd8ed1ab_0    conda-forge
flask                     1.1.2              pyh9f0ad1d_0    conda-forge
flask-compress            1.10.1             pyhd8ed1ab_0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
fsspec                    2021.11.0          pyhd8ed1ab_0    conda-forge
geos                      3.8.0                h33f27b4_0
hdf4                      4.2.15               h0e5069d_3    conda-forge
hdf5                      1.12.1          nompi_h2a0e4a3_101    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       68.2                 h0e60522_0    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
imagesize                 1.3.0              pyhd8ed1ab_0    conda-forge
importlib-metadata        4.8.2            py39hcbf5309_0    conda-forge
importlib_metadata        4.8.2                hd8ed1ab_0    conda-forge
importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
inflection                0.5.1              pyh9f0ad1d_0    conda-forge
intel-openmp              2021.4.0          h57928b3_3556    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
investpy                  1.0.6                    pypi_0    pypi
ipykernel                 6.5.0            py39h832f523_1    conda-forge
ipython                   7.29.0           py39h832f523_2    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.5              pyhd3eb1b0_1
iris                      3.0.1            py39hcbf5309_1    conda-forge
isort                     5.10.1             pyhd8ed1ab_0    conda-forge
itsdangerous              2.0.1              pyhd8ed1ab_0    conda-forge
jbig                      2.1               h8d14728_2003    conda-forge
jedi                      0.18.1           py39hcbf5309_0    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
jinja2-time               0.2.0                      py_2    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                4.2.1              pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0            py39hcbf5309_7    conda-forge
jupyter-dash              0.4.0              pyhd8ed1ab_0    conda-forge
jupyter-kite              2.0.2                    pypi_0    pypi
jupyter-packaging         0.9.0                    pypi_0    pypi
jupyter-server            1.6.1                    pypi_0    pypi
jupyter_bokeh             2.0.4                      py_0    bokeh
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_console           6.4.0              pyhd8ed1ab_1    conda-forge
jupyter_core              4.9.1            py39hcbf5309_1    conda-forge
jupyter_server            1.11.2             pyhd8ed1ab_0    conda-forge
jupyterlab                3.2.1              pyhd3eb1b0_1
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.8.2              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.0.2              pyhd8ed1ab_0    conda-forge
keyring                   23.2.1           py39hcbf5309_1    conda-forge
kiwisolver                1.3.2            py39h2e07f2f_1    conda-forge
krb5                      1.19.2               h20d022d_3    conda-forge
lazy-object-proxy         1.6.0            py39hb82d6ee_1    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libarchive                3.5.2                hb45042f_1    conda-forge
libblas                   3.9.0              12_win64_mkl    conda-forge
libcblas                  3.9.0              12_win64_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libcurl                   7.80.0               h789b8ee_0    conda-forge
libdeflate                1.8                  h8ffe710_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.9.0              12_win64_mkl    conda-forge
libmamba                  0.18.1               h44daa3b_1    conda-forge
libmambapy                0.18.1           py39h9c8ecf5_1    conda-forge
libnetcdf                 4.8.1           nompi_h1cc8e9d_101    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libsolv                   0.7.19               h7755175_5    conda-forge
libspatialindex           1.9.3                h39d44d4_4    conda-forge
libssh2                   1.10.0               h680486a_2    conda-forge
libtiff                   4.3.0                hd413186_2    conda-forge
libxml2                   2.9.12               hf5bbc77_1    conda-forge
libzip                    1.8.0                hfed4ece_1    conda-forge
libzlib                   1.2.11            h8ffe710_1013    conda-forge
llvmlite                  0.37.0           py39ha0cd8c8_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.6.3                    pypi_0    pypi
lz4-c                     1.9.3                h8ffe710_1    conda-forge
lzo                       2.10              he774522_1000    conda-forge
mamba                     0.18.1           py39hb3d9227_1    conda-forge
markupsafe                1.1.1            py39h2bbff1b_0
matplotlib                3.4.3            py39haa95532_0
matplotlib-base           3.4.3            py39h581301d_2    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
menuinst                  1.4.18           py39h59b6b97_0
mistune                   0.8.4           py39hb82d6ee_1005    conda-forge
mkl                       2021.4.0           h0e2418a_729    conda-forge
mkl-service               2.4.0            py39h6b0492b_0    conda-forge
monotonic                 1.5                        py_0    conda-forge
msgpack-python            1.0.2            py39h2e07f2f_2    conda-forge
mypy_extensions           0.4.3            py39hcbf5309_4    conda-forge
navigator-updater         0.2.1            py39haa95532_0
nbclassic                 0.3.4              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.9              pyhd8ed1ab_0    conda-forge
nbconvert                 6.3.0            py39hcbf5309_1    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
nc-time-axis              1.2.0                      py_1    conda-forge
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
netcdf4                   1.5.8           nompi_py39hf113b1f_101    conda-forge
nodejs                    16.6.1               haa95532_0
notebook                  6.4.6              pyha770c72_0    conda-forge
numba                     0.54.1           py39hb8cd55e_0    conda-forge
numbagg                   0.1                      pypi_0    pypi
numcodecs                 0.9.1            py39h415ef7b_2    conda-forge
numpy                     1.20.3           py39h6635163_1    conda-forge
numpydoc                  1.1.0                      py_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   1.1.1l               h8ffe710_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.3.4            py39h2e25243_1    conda-forge
pandoc                    2.16.1               h8ffe710_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
paramiko                  2.8.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.2              pyhd8ed1ab_0    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pathspec                  0.9.0              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.4.0            py39h916092e_0    conda-forge
pint                      0.17               pyhd8ed1ab_0    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
platformdirs              2.3.0              pyhd8ed1ab_0    conda-forge
plotly                    5.1.0              pyhd3eb1b0_0
plotly-orca               1.3.1                         1    plotly
pluggy                    1.0.0            py39hcbf5309_2    conda-forge
powershell_shortcut       0.0.1                         3
poyo                      0.5.0                      py_0    conda-forge
proj                      6.2.1                h9f7ef89_0
prometheus_client         0.12.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.22             pyha770c72_0    conda-forge
prompt_toolkit            3.0.22               hd8ed1ab_0    conda-forge
psutil                    5.8.0            py39h2bbff1b_1
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycodestyle               2.7.0              pyhd8ed1ab_0    conda-forge
pycosat                   0.6.3           py39hb82d6ee_1009    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydocstyle                6.1.1              pyhd8ed1ab_0    conda-forge
pyflakes                  2.3.1              pyhd8ed1ab_0    conda-forge
pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
pyjwt                     2.3.0              pyhd8ed1ab_0    conda-forge
pyke                      1.1.1           pyhd8ed1ab_1004    conda-forge
pylint                    2.7.2            py39hcbf5309_0    conda-forge
pyls-spyder               0.4.0              pyhd8ed1ab_0    conda-forge
pynacl                    1.4.0            py39hb3671d1_3    conda-forge
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.6              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py39hcbf5309_8    conda-forge
pyqt-impl                 5.12.3           py39h415ef7b_8    conda-forge
pyqt5-sip                 4.19.18          py39h415ef7b_8    conda-forge
pyqtchart                 5.12             py39h415ef7b_8    conda-forge
pyqtwebengine             5.12.1           py39h415ef7b_8    conda-forge
pyrsistent                0.18.0           py39hb82d6ee_0    conda-forge
pyshp                     2.1.3              pyh44b312d_0    conda-forge
pysocks                   1.7.1            py39hcbf5309_4    conda-forge
python                    3.9.7                h6244533_1
python-cufflinks          0.17.3                     py_0    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-lsp-black          1.0.0              pyhd8ed1ab_0    conda-forge
python-lsp-jsonrpc        1.0.0              pyhd8ed1ab_0    conda-forge
python-lsp-server         1.2.4              pyhd8ed1ab_0    conda-forge
python-slugify            5.0.2              pyhd8ed1ab_0    conda-forge
python-xxhash             2.0.2            py39hb82d6ee_1    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pywin32                   302              py39hb82d6ee_2    conda-forge
pywin32-ctypes            0.2.0           py39hcbf5309_1004    conda-forge
pywinpty                  1.1.6            py39h99910a6_0    conda-forge
pyyaml                    6.0              py39hb82d6ee_3    conda-forge
pyzmq                     22.3.0           py39he46f08e_1    conda-forge
qdarkstyle                3.0.2              pyhd8ed1ab_0    conda-forge
qstylizer                 0.2.1              pyhd8ed1ab_0    conda-forge
qt                        5.12.9               h5909a2a_4    conda-forge
qtawesome                 1.1.0              pyhd8ed1ab_0    conda-forge
qtconsole                 5.2.0              pyhd8ed1ab_0    conda-forge
qtpy                      1.11.2             pyhd8ed1ab_0    conda-forge
regex                     2021.11.10       py39hb82d6ee_0    conda-forge
reproc                    14.2.3               h8ffe710_0    conda-forge
reproc-cpp                14.2.3               h0e60522_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_0    conda-forge
retrying                  1.3.3                      py_2    conda-forge
rope                      0.21.1             pyhd8ed1ab_0    conda-forge
rtree                     0.9.7            py39h09fdee3_3    conda-forge
ruamel_yaml               0.15.80         py39hb82d6ee_1006    conda-forge
scipy                     1.7.1            py39hbe87c03_2
seaborn                   0.11.2             pyhd3eb1b0_0
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                59.2.0           py39hcbf5309_0    conda-forge
shapely                   1.7.1            py39h06580b3_0
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sniffio                   1.2.0            py39hcbf5309_2    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sparse                    0.12.0             pyhd8ed1ab_0    conda-forge
sphinx                    4.3.0              pyh6c4a22f_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_1    conda-forge
spyder                    5.1.5            py39haa95532_1
spyder-kernels            2.1.3            py39hcbf5309_1    conda-forge
spyder-notebook           0.1.4                      py_0    spyder-ide
sqlite                    3.36.0               h8ffe710_2    conda-forge
tbb                       2021.4.0             h2d74725_1    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
tenacity                  8.0.1              pyhd8ed1ab_0    conda-forge
terminado                 0.12.1           py39hcbf5309_1    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
text-unidecode            1.3                        py_0    conda-forge
textdistance              4.2.2              pyhd8ed1ab_0    conda-forge
three-merge               0.1.1              pyh9f0ad1d_0    conda-forge
tinycss2                  1.1.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.11               h8ffe710_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     1.2.2              pyhd8ed1ab_0    conda-forge
toolz                     0.11.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py39hb82d6ee_2    conda-forge
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
typed-ast                 1.5.0            py39hb82d6ee_0    conda-forge
typing-extensions         4.0.0                hd8ed1ab_0    conda-forge
typing_extensions         4.0.0              pyha770c72_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
udunits2                  2.2.27.27            h892ecd3_2    conda-forge
ujson                     4.2.0            py39h415ef7b_1    conda-forge
unidecode                 1.3.2              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_5    conda-forge
vega                      3.4.0            py39hcbf5309_2    conda-forge
vega_datasets             0.7.0                      py_0
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
watchdog                  2.1.6            py39hcbf5309_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.2.1            py39hcbf5309_0    conda-forge
werkzeug                  2.0.1              pyhd8ed1ab_0    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
widgetsnbextension        3.5.2            py39hcbf5309_1    conda-forge
win_inet_pton             1.1.0            py39hcbf5309_3    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.12.1           py39hb82d6ee_3    conda-forge
xarray                    0.19.0             pyhd3eb1b0_1
xmltodict                 0.12.0                     py_0    conda-forge
xxhash                    0.8.0                h8ffe710_3    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
yaml-cpp                  0.6.3                ha925a31_4    conda-forge
yapf                      0.31.0             pyhd8ed1ab_0    conda-forge
zarr                      2.8.1              pyhd3eb1b0_0
zeromq                    4.3.4                h0e60522_1    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.6.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h8ffe710_1013    conda-forge
zstd                      1.5.0                h6255e5f_0    conda-forge
```

Also I am on `Win10 x64`

**Comment by wolfv** [comment]
Great, then it's probably fixed now :)

**Comment by sirinath** [comment]
`mamba update --all` is still not working. It hangs after starting this time without any errors:

```
mamba update --all

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.18.1) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

```

Does not progress beyond the above. Using `CMD` as `Administrator`.
