### ISSUE TITLE
Micromamba sporadically hangs  (QEMU + ARM)

### ISSUE THREAD

**Issue by maresb** [mamba-org/mamba#1611]
Over at [Jupyter Docker Stacks](https://github.com/jupyter/docker-stacks/pull/1594#issuecomment-1087895999), we have been trying create the initial Conda environment for our `base-notebook` by using Micromamba instead of Miniforge. We have been plagued by sporadic hangs in our multi-arch Docker build process on GH Actions at a rate of ~20% of all runs when for `aarch64` we `RUN` the command

```bash
./micromamba install --root-prefix=/opt/conda --prefix=/opt/conda -vv --yes python=3.9 mamba notebook jupyterhub jupyterlab
```

The hang occurs sometime between the end of extraction and the beginning of linking. The last message printed during an unsuccessful run is something like

```
  #29 188.0 debug    libmamba Extracted to '/opt/conda/pkgs/mistune-0.8.4-py39h14843e3_1005'
```

without proceeding to a line like

```
#29 178.0 Linking pandoc-2.17.1.1-h8af1aa0_0
```

Execution hangs without any further output until the 6h limit is reached.

# References
(in chronological order)

* Mamba [sporadically hangs](https://github.com/jupyter/docker-stacks/issues/1539) when building jupyter/docker-stacks arm64 image
* Original [PR](https://github.com/jupyter/docker-stacks/pull/1594) in jupyter/docker-stacks to replace MiniForge with Micromamba.
* Partially [understood/isolated](https://github.com/jupyter/docker-stacks/pull/1594#issuecomment-1087895999) the problem
* This bug report
* @jonashaag [patches my jupyter/docker-stacks PR](https://github.com/jonashaag/docker-stacks/pull/1) to disable concurrency, and I confirm that it appears to work
* @jonashaag [patches libmamba](https://github.com/mamba-org/mamba/pull/1616) to disable subprocesses when `extract_threads=1`
* Discussion returns to this thread

**Comment by jonashaag** [comment]
Is it possible for you to try to reproduce the error with concurrency = 1 for everything that involves concurrency (extract, download, …)?

**Comment by maresb** [comment]
Hi @jonashaag, thanks so much for helping! I am looking into the config, and I see `download_threads` and `extract_threads`. Is this what you mean? Are there any other values you suggest?

I also see a configuration called `lock_timeout` which defaults to `0( (no timeout)`. It seems plausible to me that there is a deadlock, so I wonder if this parameter could also be interesting. But first I will try with `download_threads` and `extract_threads` 1.

**Comment by maresb** [comment]
@jonashaag, I still had a failure with `download_threads=1` and `extract_threads=1`. I will try with `lock_timeout=300`...

**Comment by maresb** [comment]
@jonashaag no success with `lock_timeout=300`. Any other ideas?

**Comment by jonashaag** [comment]
Hmm, I can try to have a look at it if it's reproducible on my machine. Can you give instructions how to reproduce? Local Docker setup would be easiest I guess.

**Comment by maresb** [comment]
It is not so easy to reproduce, and like I said it's sporadic (~20%). My current technique is to spawn 10 GH Actions instances from 10 identical branches and hope that one or more hangs. From [here](https://github.com/maresb/docker-stacks/actions) you can see that runs 70 and 71 timed out at 6h.

(For some of my runs in the past, I cancelled before the 6h timeout when it was already clear that some instances were hung.)

Another piece of potentially very relevant information: we have also noticed [similar issues](https://github.com/jupyter/docker-stacks/issues/1539) with `mamba` (not just `micromamba`) on `aarch64` after upgrading from `v0.17` to `v0.18`.

**Comment by jonashaag** [comment]
> I believe that `v0.17` is unaffected.

If 0.18 is affected then it's likely this is because of parallel extraction.

> That's a bit too involved for me. Unfortunately I'm very inexperienced with C++ debugging.

In this case it's really simple, just delete the lines of code I've highlighted and fix the braces.

**Comment by maresb** [comment]
> In this case it's really simple, just delete the lines of code I've highlighted and fix the braces.

It doesn't seem that simple to me... correct me if I'm wrong, but not only would I need to delete the highlighted code, but I would also have to cross-compile to aarch64 (which is currently done via the Conda-Forge infrastructure), and ensure that it's linked in such a way that I can successfully download and execute it from the GHA instance.

Is there any possibility to add a config option to disable parallel extraction, and then I can turn on that flag once the next release comes out? That seems to me like a much more practical way to proceed (unless you have a simpler suggestion?).

**Comment by maresb** [comment]
Continuation: https://github.com/jonashaag/docker-stacks/pull/1

**Comment by maresb** [comment]
Discussion resumes from [here](https://github.com/mamba-org/mamba/pull/1616).

Annoyingly, the `docker buildx build` command from [here](https://github.com/mamba-org/mamba/pull/1616#issuecomment-1093412406) doesn't produce any debugging output, even with `-vvv` enabled. I'm not sure why, but this is all I get:

![image](https://user-images.githubusercontent.com/15216687/162568030-2b0e987f-d474-4c36-b044-c38ea460ede2.png)

(Sorry from the screenshot, the progress bars seem to make it impossible for me to copy the text.)

Now for some great news, I managed to reproduce it with `docker run`!
![image](https://user-images.githubusercontent.com/15216687/162568094-a7b38736-3c91-433f-8beb-bf0177131630.png)

I truncated the Dockerfile up to but not including the `./micromamba install` command. Then on a loop I ran

```bash
docker run --rm -it --platform "linux/arm64" debug-micromamba-arm64 ./micromamba install --root-prefix=/opt/conda -c conda-forge --prefix=/opt/conda -vvv --yes python=3.9 mamba notebook jupyterhub jupyterlab
```

until it hung.

It's cycling between `jupyter_telemetry`, `libffi`, `certifi`, `jinja2`, and `jsonschema`. I can `docker exec` into the container, so if we wrote logs to files, it would be very easy to read them.

@jonashaag any ideas for how to move forward? I see a few potential approaches: I may be able to work towards a more minimal and reliable way to reproduce the problem, and/or maybe you could work on some logging to figure out exactly where in the code it's getting stuck?

**Comment by maresb** [comment]
I was doing a loop where I repeatedly installed `nodejs`. It froze with the following:
![image](https://user-images.githubusercontent.com/15216687/162569871-c4dba762-d70b-4c76-b8e2-63381ceae826.png)
This looks bad, no?

**Comment by wolfv** [comment]
Hey @maresb std::bad_alloc usually means running out of memory (RAM)...

Is there a way to give the QEMU more RAM? I think `buildx` has a `--memory` flag.

**Comment by wolfv** [comment]
btw you could also add `CI=1` to the env vars to get rid of the progress bars and get only text output.

**Comment by maresb** [comment]
Thanks for the suggestions @wolfv!

The `std::bad_alloc` occurs in `docker run`, not `docker build`, so `buildx` is not in play.

I'm short on time at the moment, but I did a little poking around. (I'm running Ubuntu.) Inside the container, running `free` gives the same result as on the host. So I'm wondering how it's running out of memory if it's sharing the memory on the host. Digging into it slightly further, I see that the binaries are being executed with `qemu-aarch64-static`. Running `qemu-aarch64-static --help` it looks like there are some interesting options:

```
usage: qemu-aarch64 [options] program [arguments...]
Linux CPU emulator (compiled for aarch64 emulation)

Options and associated environment variables:

Argument             Env-variable      Description
-h                                     print this help
-help                                  
-g port              QEMU_GDB          wait gdb connection to 'port'
-L path              QEMU_LD_PREFIX    set the elf interpreter prefix to 'path'
-s size              QEMU_STACK_SIZE   set the stack size to 'size' bytes
-cpu model           QEMU_CPU          select CPU (-cpu help for list)
-E var=value         QEMU_SET_ENV      sets targets environment variable (see below)
-U var               QEMU_UNSET_ENV    unsets targets environment variable (see below)
-0 argv0             QEMU_ARGV0        forces target process argv[0] to be 'argv0'
-r uname             QEMU_UNAME        set qemu uname release string to 'uname'
-B address           QEMU_GUEST_BASE   set guest_base address to 'address'
-R size              QEMU_RESERVED_VA  reserve 'size' bytes for guest virtual address space
-d item[,...]        QEMU_LOG          enable logging of specified items (use '-d help' for a list of items)
-dfilter range[,...] QEMU_DFILTER      filter logging based on address range
-D logfile           QEMU_LOG_FILENAME write logs to 'logfile' (default stderr)
-p pagesize          QEMU_PAGESIZE     set the host page size to 'pagesize'
-singlestep          QEMU_SINGLESTEP   run in singlestep mode
-strace              QEMU_STRACE       log system calls
-seed                QEMU_RAND_SEED    Seed for pseudo-random number generator
-trace               QEMU_TRACE        [[enable=]<pattern>][,events=<file>][,file=<file>]
-version             QEMU_VERSION      display version information and exit

Defaults:
QEMU_LD_PREFIX  = /etc/qemu-binfmt/aarch64
QEMU_STACK_SIZE = 8388608 byte

You can use -E and -U options or the QEMU_SET_ENV and
QEMU_UNSET_ENV environment variables to set and unset
environment variables for the target process.
It is possible to provide several variables by separating them
by commas in getsubopt(3) style. Additionally it is possible to
provide the -E and -U options multiple times.
The following lines are equivalent:
    -E var1=val2 -E var2=val2 -U LD_PRELOAD -U LD_DEBUG
    -E var1=val2,var2=val2 -U LD_PRELOAD,LD_DEBUG
    QEMU_SET_ENV=var1=val2,var2=val2 QEMU_UNSET_ENV=LD_PRELOAD,LD_DEBUG
Note that if you provide several changes to a single variable
the last change will stay in effect.

See <https://qemu.org/contribute/report-a-bug> for how to report bugs.
More information on the QEMU project at <https://qemu.org>.
```

If I understand correctly, `qemu` is allocating some fixed virtual address space, and if this runs out, then the executable cannot allocate more memory? So maybe it would help if we specified the size here?

One potential difficulty is that I'm not calling this directly, it's being called via `docker run`, so hopefully by setting either the envvars on the host or container I could access these options. But I'm a bit lost with the system-level memory management stuff since most of my experience is with higher-level languages.

I don't have more time at the moment, but wanted to give an update on my current progress.

**Comment by jonashaag** [comment]
@maresb can you let me know roughly what hardware specs your machine has? What CPU and number of cores/threads? RAM?

**Comment by jonashaag** [comment]
Oh and what are the CPU/RAM limits configured in Docker?

**Comment by maresb** [comment]
CPU:
```
Intel Skylake Processeur Core i7-6700 / 3.4 GHz (Turbo Boost 4.0 GHz) 4 cœurs 8Mo Cache Socket Socket 1151 (BX80662I76700)
```
RAM: 64GB

CPU/RAM limits: None! That's the beauty of Docker on Linux. :wink: 

I think the real question is what are the RAM limits being imposed by QEMU. Sorry I don't have time to dig into this more at the moment.

**Comment by jonashaag** [comment]
I can reproduce this, now looking into causes.

**Comment by jonashaag** [comment]
_Maybe_ it is because we aren't using `reproc::sink::thread_safe::string(out)` here https://github.com/mamba-org/mamba/blob/d1a568b72f451e0b560fc45f32dcd33e4c2211d4/libmamba/src/core/package_handling.cpp#L454-L455

**Comment by wolfv** [comment]
@jonashaag any chance you can elabortae how you were able to reproduce this? E.g. also running in QEMU with limited RAM or natively?

For the `thread_safe::string` – `out` and `err` are local variables to the function so I don't think that any multithreading should be involved at that level but I might also be wrong. Let's see what @JohanMabille thinks!

Thanks for the debugging!!

**Comment by jonashaag** [comment]
How to reproduce

- Checkout https://github.com/jonashaag/docker-stacks/tree/dbg
- Checkout https://github.com/jonashaag/mamba/tree/dbg to `base-notebooks`
- Run `./build` (maybe change path of `build` cmd to `docker buildx`; my Docker install didn't have `buildx`)
- Run `./run` (I used an 8 core x64 CPU)

**Comment by jonashaag** [comment]
> For the `thread_safe::string` – `out` and `err` are local variables to the function so I don't think that any multithreading should be involved at that level

That's what I'm thinking as well and I have been able to reproduce the deadlock with `thread_safe::` tonight. Maybe there is a bug in stdout/stderr redirection in `reproc` even with `thread_safe::` because I haven't been able to reproduce the deadlock when stdout/stderr is simply forwarded to `cout`. But will try a little more.

**Comment by jonashaag** [comment]
> How to reproduce

Note that you can also pass `-e QEMU_TRACE=1` to Docker but it is incredibly slow and I haven't been able to reproduce the deadlock with that option so far (maybe not enough runs)

**Comment by jonashaag** [comment]
It looks like a problem with reproc. If I replace reproc with `std::system` I can't reproduce. Where exactly in reproc I don't know though.

**Comment by jonashaag** [comment]
From the logs it looks like sometimes a tiny number of extraction processes are not started properly. Maybe there is a deadlock or something in the reproc process starting code.

**Comment by jonashaag** [comment]
Can confirm that the deadlock happens in `reproc::process.start`.

**Comment by wolfv** [comment]
@jonashaag awesome. Just to confirm, this happens _before_ the process actually starts, right? Because there is some (file-based) locking code when invoking the `micromamba package extract` command to prevent two processes from extracting the same tarball.

**Comment by jonashaag** [comment]
It happens somewhere between https://github.com/DaanDeMeyer/reproc/blob/89dc11aed97e8c9efca2084c46431e43071a3d3c/reproc%2B%2B/include/reproc%2B%2B/run.hpp#L15 and https://github.com/mamba-org/mamba/blob/3bb7aab0d4a3ce6715ab50215507b66f1f6e8d21/micromamba/src/package.cpp#L26

**Comment by jonashaag** [comment]
According to print output, this line sometimes doesn't work (child never returns from `fork()`) https://github.com/DaanDeMeyer/reproc/blob/3eabeb38f44f9920a2d7dc10e70498d7512b453f/reproc/src/process.posix.c#L166

**Comment by wolfv** [comment]
Maybe something like this could be related https://bugs.launchpad.net/qemu/+bug/1915531

**Comment by wolfv** [comment]
Out of curiosity if you use `export G_SLICE=always-malloc` (I think outside docker) does that change things?

**Comment by wolfv** [comment]
The bug report has migrated to gitlab: https://gitlab.com/qemu-project/qemu/-/issues/285

**Comment by jonashaag** [comment]
It seems to fix it, I've let a round of 20 runs run with these settings

```
export G_SLICE=always-malloc
docker run ... bash -c 'env G_SLICE=always-malloc ./micromamba install ...'
```

and it didn't hang. I'm going to do another round of 20 runs.

**Comment by jonashaag** [comment]
Assuming that this is the fix and we don't want to wait for a fix in Qemu, what are our options?

- Workaround in Mamba
  - Have a single "reproc starter thread" that we delegate reproc calls to? (Not sure if that fixes the problem)
  - Try to detect Qemu and disable parallel extraction?
  - Reduce number of subprocesses that are created, e.g. only do in subprocess if archive size is above a certain threshold, or batch multiple extractions into a single subprocess call. (Also not sure if that fixes anything and how robust it is)
- Workaround in reproc
  - Require `G_SLICE=always-malloc` in Qemu?
  - ?

**Comment by wolfv** [comment]
Can we fix docker buildx?

**Comment by jonashaag** [comment]
It isn’t a problem with buildx only, is it? It’s also a problem in docker run.

**Comment by jonashaag** [comment]
And all other uses of Qemu outside Docker, eg in ARM CI pipelines when you only have x86 hardware.

**Comment by jonashaag** [comment]
`G_SLICE=always-malloc` seems to make the problem go away. @maresb can you try this in your setup as well?

**Comment by wolfv** [comment]
First of all, thanks a ton for testing & debugging this @jonashaag 
Looks like this is a really unfortunate bug.

I see two options:

- document that this is a problem with qemu and that one should set that env var
- automatically use the main thread for extraction when we detect that the binary is ran in qemu (I suspect there might be some env vars we could check for that?)


Additionally I am wondering if a later qemu or qemu with a different glib might fix this but I have no idea how docker buildx is put together.

**Comment by wolfv** [comment]
I posted in the qemu issue: https://gitlab.com/qemu-project/qemu/-/issues/285#note_919207579

**Comment by jonashaag** [comment]
This seems to be the proper way to detect Qemu https://stackoverflow.com/questions/70116861/how-do-i-detect-qemu-emulation-from-within-a-docker-container

**Comment by maresb** [comment]
Hey, sorry for the long silence, I've been quite busy, but I managed to run some extensive tests last night! :rocket: 

I confirm that on my system, after compiling from `master`, either of the two options below work to prevent hangs within Docker/QEMU for `--platform=linux/arm64`:

1. `micromamba config set extract_threads 1 && micromamba install` (105 consecutive runs without hanging)
2. `env G_SLICE=always-malloc micromamba install` (156 consecutive runs without hanging)

To clarify, I do not need to set `G_SLICE=always-malloc` on the host, it suffices to set it just for running the `micromamba install` command.

Also, one of the two above solutions is indeed _necessary_ to prevent hangs.

**Comment by jonashaag** [comment]
Confusion party! Yes indeed I assumed with latest `master` no workarounds would be required anymore. Will start a few more runs to debug further...

**Comment by maresb** [comment]
:partying_face:

I confirm that I'm asserting that, assuming I didn't make a mistake, workarounds are unfortunately still required.

In case you want to check my work, it's [in this commit](https://github.com/maresb/docker-stacks/commit/a2c6bfdffaef9b5a83cfb1cf3aa420abcfd38e91). (Run `./build`, `./run` and `./run2`.)

**Comment by maresb** [comment]
@wolfv, it appears that I did make a mistake. Between old and new branches, it seems I got something crossed, and ended up testing the old Micromamba executable used for bootstrapping the build environment. :facepalm:. Thanks @jonashaag for checking my work and pointing this out.

I'm rerunning the tests now with the correct executable, and I'll try to report the results this evening.

My working assumption is that this issue has now been resolved in master, and hopefully my tests will confirm this. Sorry for the confusion! :balloon:  :partying_face: :man_dancing:

**Comment by maresb** [comment]
In particular, please don't delay any potential releases on account of this issue. :smile:

**Comment by wolfv** [comment]
Thanks @maresb – we're not delaying a release, no worries. Still fighting some other threading related problems :)
But it would be awesome if this is automagically fixed by the next release :)

**Comment by maresb** [comment]
Unfortunately, after rerunning the tests [with the correct binary](https://github.com/maresb/docker-stacks/commit/dab031afba9278d40b35b601be2711b7f760a79b), I coincidentally arrive at [the same conclusion as before](https://github.com/mamba-org/mamba/issues/1611#issuecomment-1112970540).

**Comment by mathbunnyru** [comment]
We noticed that `extract_threads: 1` works well for `micromamba`, but not for `mamba` (we still get stuck builds).
We were setting it as `./micromamba config set extract_threads 1` and it created `~/.condarc` file with this setting. I think mamba reads this config file as well, so I'm not sure why it didn't work for `mamba`.

`G_SLICE=always-malloc` works reliably.

**Comment by mathbunnyru** [comment]
The way to reproduce this (thanks to @maresb) is described here:
https://github.com/jupyter/docker-stacks/pull/1697/files#issuecomment-1115843449

**Comment by marcelotrevisani** [comment]
For me it hangs when I create an environment with ``vs2015_runtime-14.29.30037``, it hangs in the linking phase

**Comment by jonashaag** [comment]
Can you please open another issue. This one is very specific to running in QEMU.

**Comment by maresb** [comment]
From the jupyter/docker-stacks side this issue is no longer relevant since @mathbunnyru switched the ARM builds from QEMU emulation to native runners. That's why there's been no activity for several months.

@marcelotrevisani, does it still hang if you downgrade to micromamba v0.17? (There were some changes in v0.18.)

**Comment by jonashaag** [comment]
@maresb we still expect the problem to exist in other QEMU setups, right? Do you remember if we have anything to do here (fix something, add docs, …)

**Comment by maresb** [comment]
The current status is unclear. I once reproduced the hang using the instructions from the link a few comments above, but I never managed to replicate it after that.

My impression is that the patches you wrote vastly improved the problem, if not solved it. We still observed some hangs in jupyter/docker-stacks subsequent to your patches, but those may have been due to a separate problem where the chained Docker images were being built from stale base images. That problem was fixed at the same time as the introduction of ARM runners, so I don't think we can say much from the jupyter/docker-stacks side. But @mathbunnyru was much more deeply involved with that, so perhaps he can correct what I'm saying or has additional ideas.

I do have the impression that there may still be some very rare edge case still triggers a hang. But unless someone has a better reproducer, I think further investigation would require running lots of overnight experiments.

**Comment by jonashaag** [comment]
Thanks @maresb! Mind reviewing #1873?

**Comment by corneliusroemer** [comment]
For me, on macOS 13.5 on arm64, only workaround 1) from above: `micromamba config set extract_threads 1 && micromamba install` works.

Using `env G_SLICE=always-malloc micromamba install`, I get hangs.

This is my dockerfile:
```
FROM mambaorg/micromamba:1.4.9
COPY environment.yml /environment.yml
micromamba config set extract_threads 1
RUN env G_SLICE=always-malloc micromamba create -vv -y -n pangolin -f /environment.yml 
```
