### ISSUE TITLE
doc: Recent release 1.1.0 does not appear in Github release list 

### ISSUE THREAD

**Issue by corneliusroemer** [mamba-org/mamba#2151]
See https://github.com/mamba-org/mamba/releases where 1.1.0 is missing

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/25161793/205459906-bbf3ad88-700b-45ce-9d2b-7403abe0e623.png">

**Comment by RoyiAvital** [comment]
Where is the release notes of 1.1?

**Comment by corneliusroemer** [comment]
Here @RoyiAvital https://github.com/mamba-org/mamba/blob/main/CHANGELOG.md

**Comment by wolfv** [comment]
fixed yesterday, sorry.

**Comment by corneliusroemer** [comment]
Almost! 1.1.0 is somehow still not set as `latest` hence not showing on the front page:
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/25161793/211754659-068676f1-0cf5-420f-8455-c0f774b3ce13.png">
