### ISSUE TITLE
"Non-conda folder exists at prefix" after aborted env creation with `--platform`

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/mamba#2736]
With Micromamba 1.4.9, on osx-arm64:

```
$ micromamba create -p /tmp/env --platform osx-64 zlib
Confirm changes: [Y/n] n  <=== abort this
$ micromamba create -p /tmp/env --platform osx-64 zlib
error    libmamba Non-conda folder exists at prefix
```

**Comment by Hind-M** [comment]
Can you specify the context of the environment creation failure? (logs of failure for example)

**Comment by jonashaag** [comment]
Updated the instructions, key seems to be to select another platform

**Comment by jonashaag** [comment]
This issue just re-appeared in a recent 1.x version:

```
$ micromamba -p /tmp/env create -f environment.yml --platform win64
...
error    libmamba Platform is ill-formed, expected <os>-<arch> in: 'win64'
error    libmamba Could not solve for environment specs
...
$ micromamba -p /tmp/env create -f environment.yml --platform win-64
error    libmamba Non-conda folder exists at prefix
critical libmamba Aborting.
```

That's exactly why I always advocate for adding regression tests for bug fixes.

**Comment by sufyazi** [comment]
hi, I am having this issue. I tried creating an env with the --platform flag, but it failed at first because of a nonexistent package. After removing the offending package and rerunning the same command, I got this `non-conda folder exists at prefix`. What should I do?

**Comment by corneliusroemer** [comment]
Please please fix this, it's super annoying to have to track down the exact prefix and manually delete it when micromamba create errors. It should clean up after itself when erroring with an expectable install problem rather than just crashing.

Example:

```
$ micromamba create -n ingest -f environment.yml --rc-file .mambarc --platform osx-64
Found conda-prefix at '/Users/corneliusromer/micromamba/envs/ingest'. Overwrite?: [y/N] y
bioconda/osx-64 (check zst)                        Checked  0.1s
bioconda/noarch (check zst)                         Checked  0.2s
bioconda/noarch                                      5.3MB @   3.7MB/s  1.4s
bioconda/osx-64                                      4.6MB @   2.7MB/s  1.7s
conda-forge/noarch                                  15.4MB @   4.0MB/s  3.9s
conda-forge/osx-64                                  31.7MB @   6.2MB/s  5.1s
error    libmamba Could not solve for environment specs
    The following package could not be installed
    └─ orjsonl does not exist (perhaps a typo or a missing channel).
critical libmamba Could not solve for environment specs

$ micromamba create -n ingest -f environment.yml --rc-file .mambarc --platform osx-64
error    libmamba Non-conda folder exists at prefix
critical libmamba Aborting.

$ rm -rf /Users/corneliusromer/micromamba/envs/loculus-ingest

$ micromamba --version
1.5.8
```

**Comment by rjlopez2** [comment]
I am also facing some issues here. not sure how to fix it yet.

this works for me on windows device:
```
$ micromamba create -p D:\test\my_env -f .\requirements.yml
```
But this does not, even thought the folder does exists:
```
$ micromamba create -p 'D:\User_R\OneDrive - Universitaet Bern\place\of\working\space\loc_venv' -f .\requirements.yml
>error    libmamba Non-conda folder exists at prefix
>critical libmamba Aborting.
```
That's all information I received. I do noted that the path has spaces in the strings. Changing to double quote, does not help.

My micromamba version = 1.5.8

Please some help would be appreciated.
thanks

**Comment by sufyazi** [comment]
Not the dev, but have you tried manually looking into the folder structure and manually deleting loc_venv dir before rerunning `micromamba create`? That's the workaround that worked for me (as I posted above).

**Comment by corneliusroemer** [comment]
@rjlopez2 you simply have to delete the folder manually, i.e. with `rm -rf foldername`

It's annoying that this is necessary but it should work as a workaround.

**Comment by rjlopez2** [comment]
My bad, I read this way too fast.
thanks a lot @corneliusroemer and @sufyazi.
removing the existing folder works.
👍

**Comment by corneliusroemer** [comment]
Thanks for reminding everyone about the pervasiveness and the annoyance of this issue though. It's a really big bug that should have been fixed long ago.

@Hind-M I know you're close to releasing V2 - is it fixed there at least?

**Comment by anna-parker** [comment]
I'm sadly still seeing this bug on 
```
micromamba --version
1.5.10
```
Even though according to the tags, the fix https://github.com/mamba-org/mamba/pull/2738 should be included in this micromamba version. 

environment creation failed, and then I could not create micromamba again until I deleted the folder 
```
$ micromamba create -f environment.yml --platform=linux/amd64
bioconda/linux/amd64 (check zst)                    Checked  0.6s
[+] 0.2s
conda-forge/linux/amd64 ━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0.0 B /  ??.?MB @  ??.?MB/s  0.2s
conda-forge/linux/amd64                             ??.?MB @  ??.?MB/s 404 failed  0.3s
bioconda/linux/amd64                               359.0 B @ 540.0 B/s 404 failed  0.7s
bioconda/noarch                                      4.4MB @ 377.5kB/s 11.6s
conda-forge/noarch                                  16.8MB @ 991.9kB/s 17.0s
error    libmamba Platform is ill-formed, expected <os>-<arch> in: 'linux/amd64'
error    libmamba Could not solve for environment specs
...
$ micromamba create -f environment.yml --platform=linux/amd64
error    libmamba Non-conda folder exists at prefix
critical libmamba Aborting.
```
thanks @sufyazi for the tip!

**Comment by jjerphan** [comment]
This has been fixed in 2.0 (I cannot reproduce the issue with 2.0.4).

Feel free to reopen an issue with a reproduce if you still have this issue.

Note that 1.x is note being developed anymore, but to address security fixes.

**Comment by corneliusroemer** [comment]
I'm still seeing this on micromamba v2.1.1

Repro:

```yaml
# environment.yml
name: freyja-sc2
channels:
    - bioconda
    - bioconda
dependencies:
  - bioconda::cutadapt
  - bioconda::freyja
  - bioconda::minimap2
  - bioconda::sra-tools
  - conda-forge::pigz
  - conda-forge::python
  - conda-forge::pyarrow
  - conda-forge::google-cloud-sdk
  - pip
  - pip:
    - epiweeks
    - pandas
    - frozendict
    - git+https://github.com/outbreak-info/python-outbreak-info
```

```sh
micromamba create -f environment.yml --platform osx-64
```

This will fail, then afterwards try to rerun:

```sh
micromamba create -f environment.yml --platform osx-64
```

and you'll get

```
error    libmamba Non-conda folder exists at prefix
critical libmamba Aborting.
```
