### ISSUE TITLE
[micromamba] micromamba can't read .yml files without name entries

### ISSUE THREAD

**Issue by asford** [mamba-org/mamba#598]
Micromamba supports environment.yml files. 🥳 Killer feature!

We frequently use `environment.yml` files to specify reproducible environments that only include `dependencies` and `channels` entries. This works with `conda env create` with explicit `--prefix` and `--name` overrides. However, in `micromamba` this throws a somewhat-hard-to-understand `YAML::TypedBadConversion` error.

I *think* the expected behavior would match `conda env create`. The `name:` entry in environment.yml is optional and strictly overridden by the  `--prefix` and `--name` options command-line options.

### Detailed Repro

```
#!/bin/bash
#http://redsymbol.net/articles/unofficial-bash-strict-mode/

set -euo pipefail
IFS=$'\n\t'

# Setup micromamba
wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
export MAMBA_ROOT_PREFIX=`pwd`/mamba-root

cat - > env_no_name.yml <<EOF
channels:
- conda-forge
dependencies:
- python=3.8.5
EOF

cat - > env_name.yml <<EOF
name: test-env
channels:
- conda-forge
dependencies:
- python=3.8.5
EOF

cat - > env_blank_name.yml <<EOF
name: ""
channels:
- conda-forge
dependencies:
- python=3.8.5
EOF


set +e

echo  Error case: "--prefix" specified in args but no "name:", conda env creates env at prefix

set -x
bin/micromamba create --yes --prefix env_no_name --file env_no_name.yml
conda env create --prefix env_no_name_conda --file env_no_name.yml
set +x

echo  Error case: "--prefix" specified in args but env.yml has "name:", conda env creates env at prefix

set -x
bin/micromamba create --yes --prefix env_name --file env_name.yml
conda env create --prefix env_name_conda --file env_name.yml
set +x

echo  Workaround case: "--prefix" specified but env.yml has name: \"\"

set -x
bin/micromamba create --yes --prefix env_blank_name --file env_blank_name.yml
conda env create --prefix env_blank_name_conda --file env_blank_name.yml
set +x
```

**Comment by wolfv** [comment]
PR's welcome! :)

**Comment by asford** [comment]
Notes for future self:

The YAML read error is being thrown at:

https://github.com/mamba-org/mamba/blob/0.7.2/src/micromamba/main.cpp#L874

This can be fixed by checking [`if (config["name"])`](https://github.com/jbeder/yaml-cpp/wiki/Tutorial).

`create_options` has already been partially populated from the command line, so we can bypass `name:` parsing if already specified.

**Comment by wolfv** [comment]
Fixed!

**Comment by Servinjesus1** [comment]
:( still happening in 1.1.0
![image](https://user-images.githubusercontent.com/8541095/208164745-9b2ba739-c5ce-43ca-a1c5-824efbbcc457.png)
